version: '3.9'
name: golang-template

services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    command: ['postgres', '-c', 'log_statement=all']

  pgAdmin:
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '127.0.0.1:5050:5050'
    depends_on:
      - db
    volumes:
        - pg-admin-data:/pgadmin4/servers.json
    logging:
      driver: none

volumes:
  postgres-db:
    name: postgres-db
  pg-admin-data:
    name: pg-admin-data